/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MovieInput = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'genre' : IDL.Text,
  'rating' : IDL.Float64,
  'videoUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Movie = IDL.Record({
  'id' : IDL.Nat,
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'genre' : IDL.Text,
  'rating' : IDL.Float64,
  'videoUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMovie' : IDL.Func([MovieInput], [IDL.Nat], []),
  'addToWatchlist' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMovie' : IDL.Func([IDL.Nat], [], []),
  'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContinueWatching' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getFeaturedMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMovieById' : IDL.Func([IDL.Nat], [Movie], ['query']),
  'getMoviesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlistIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWatchlist' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMoviesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  'updateContinueWatching' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateMovie' : IDL.Func([IDL.Nat, MovieInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MovieInput = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'genre' : IDL.Text,
    'rating' : IDL.Float64,
    'videoUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Movie = IDL.Record({
    'id' : IDL.Nat,
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'genre' : IDL.Text,
    'rating' : IDL.Float64,
    'videoUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMovie' : IDL.Func([MovieInput], [IDL.Nat], []),
    'addToWatchlist' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMovie' : IDL.Func([IDL.Nat], [], []),
    'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContinueWatching' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getFeaturedMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMovieById' : IDL.Func([IDL.Nat], [Movie], ['query']),
    'getMoviesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlistIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWatchlist' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMoviesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
    'updateContinueWatching' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateMovie' : IDL.Func([IDL.Nat, MovieInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };