/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Movie {
  'id' : bigint,
  'categories' : Array<string>,
  'title' : string,
  'duration' : bigint,
  'thumbnailUrl' : string,
  'year' : bigint,
  'description' : string,
  'isFeatured' : boolean,
  'genre' : string,
  'rating' : number,
  'videoUrl' : string,
}
export interface MovieInput {
  'categories' : Array<string>,
  'title' : string,
  'duration' : bigint,
  'thumbnailUrl' : string,
  'year' : bigint,
  'description' : string,
  'isFeatured' : boolean,
  'genre' : string,
  'rating' : number,
  'videoUrl' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMovie' : ActorMethod<[MovieInput], bigint>,
  'addToWatchlist' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMovie' : ActorMethod<[bigint], undefined>,
  'getAllMovies' : ActorMethod<[], Array<Movie>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContinueWatching' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getFeaturedMovies' : ActorMethod<[], Array<Movie>>,
  'getMovieById' : ActorMethod<[bigint], Movie>,
  'getMoviesByCategory' : ActorMethod<[string], Array<Movie>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlistIds' : ActorMethod<[], Array<bigint>>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromWatchlist' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMoviesByTitle' : ActorMethod<[string], Array<Movie>>,
  'updateContinueWatching' : ActorMethod<[bigint, bigint], undefined>,
  'updateMovie' : ActorMethod<[bigint, MovieInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];